export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'

export const REQUEST_REDUX_PENDING = 'REQUEST_REDUX_PENDING'
export const REQUEST_REDUX_SUCCESS = 'REQUEST_REDUX_SUCCESS'
export const REQUEST_REDUX_FAILED = 'REQUEST_REDUX_FAILED'